In [57]:
import numpy as np

In [58]:
inputfile = open(r'input.txt', 'r')
inputdata = np.asarray([line.strip() for line in inputfile])

In [59]:
safe = 0
for input in inputdata:
    report = np.asarray([int(level) for level in input.split()])
    if np.all((report == np.sort(report)) | (report == np.sort(report)[::-1])):
        differences = np.convolve(report, [-1, 1], mode='valid')
        if np.all((differences >= -3) & (differences <= 3) & (differences != 0)):
            safe += 1
print(safe)

2


In [ ]:
safe = 0
for input in inputdata:
    report = np.asarray([int(level) for level in input.split()])
    passed = False

    # passes without problem dampener
    if np.all((report == np.sort(report)) | (report == np.sort(report)[::-1])):
        differences = np.convolve(report, [-1, 1], mode='valid')
        if np.all((differences >= -3) & (differences <= 3) & (differences != 0)):
            safe += 1
            print(report)
            continue
    
    # check if it passes with dampener
    for i in range(len(report)):
        if passed: break
        mask = (np.arange(len(report)) == i) ^ 1
        modified_report = report[mask == 1]
        if np.all((modified_report == np.sort(modified_report)) & (modified_report == np.sort(modified_report)[::-1])):
            differences = np.convolve(modified_report, [-1, 1], mode='valid')
            if np.all((differences >= -3) & (differences <= 3) & (differences != 0)):
                safe += 1
                passed = True
                print(modified_report)
                print(np.sort(modified_report))
print(safe)


[7 6 4 2 1]
[1 2 4 5]
[1 2 4 5]
[8 6 4 1]
[1 4 6 8]
[1 3 6 7 9]
[5 7 5 8]
[5 5 7 8]
5
